# Generated by Django 6.0.7 on 2026-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracker_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WaitingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=500)),
                ('reason', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracker_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
