# Generated by Django 6.0.7 on 2026-07-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitingtask',
            name='duration_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitingtask',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
